parameters:
    # Defaults
    env(AUDIT_PHPCS_PARALLEL): 1
    # Get from env()
    secret: "%env(SECRET)%"
    mailer_transport: "%env(MAILER_TRANSPORT)%"
    mailer_host: "%env(MAILER_HOST)%"
    mailer_user: "%env(MAILER_USER)%"
    mailer_password: "%env(MAILER_PASSWORD)%"
    aws_sqs_version: "%env(AWS_SQS_VERSION)%"
    aws_sqs_region: "%env(AWS_SQS_REGION)%"
    aws_sqs_key: "%env(AWS_SQS_KEY)%"
    aws_sqs_secret: "%env(AWS_SQS_SECRET)%"
    aws_sqs_queue_name: "%env(AWS_SQS_QUEUE_NAME)%"
    aws_s3_version: "%env(AWS_S3_VERSION)%"
    aws_s3_region: "%env(AWS_S3_REGION)%"
    aws_s3_key: "%env(AWS_S3_KEY)%"
    aws_s3_secret: "%env(AWS_S3_SECRET)%"
    aws_s3_bucket_name: "%env(AWS_S3_BUCKET_NAME)%"
    tide_api_key: "%env(TIDE_API_KEY)%"
    tide_api_secret: "%env(TIDE_API_SECRET)%"
    tide_api_auth_url: "%env(TIDE_API_AUTH_URL)%"
    tide_api_connect_timeout: "%env(TIDE_API_CONNECT_TIMEOUT)%"
    audit_email_sender: "%env(AUDIT_EMAIL_SENDER)%"
    audit_scripts_path: "%env(AUDIT_SCRIPTS_PATH)%"
    audit_standards_path: "%env(AUDIT_STANDARDS_PATH)%"
    audit_stats_path: "%env(AUDIT_STATS_PATH)%"
    audit_phpcs_parallel: "%env(AUDIT_PHPCS_PARALLEL)%"